### ISSUE TITLE
refactor : Deal API 리펙토링 초기 설정

### ISSUE THREAD

**Issue by Kwontaehwon** [SWM-ChocoBread/N_bread_Server#184]
## 🔑Description
거래 관련 (/api/deals) API 리펙토링 초기 설정 및 적용

<br>

## ✅TODO List
- [ ] Route, Repository, Service 분리
- [ ] Dto, Param 추가
- [ ] `require`문 ES6 문법에 맞게 `import`로 변경
