### ISSUE TITLE
Docker 테스트 적용

### ISSUE THREAD

**Issue by Kwontaehwon** [SWM-ChocoBread/N_bread_Server#203]
## 🔑Description
Docker 컨테이너를 이용한 테스트 DB 사용

<br>

## ✅TODO List
- [ ] 테스트 DB용 env 생성
- [ ] docker-compose 파일 생성
- [ ] 테스트 수행 script 작성
- [ ] Docker 컨테이너로 테스트 DB 생성
- [ ] 새로운 테스트 DB에서 모든 테스트 통과 확인
