### ISSUE TITLE
거래 참여, 수정, 신고 리펙토링

### ISSUE THREAD

**Issue by Kwontaehwon** [SWM-ChocoBread/N_bread_Server#205]
## 🔑Description

거래 참여, 수정, 신고 리펙토링

<br>

## ✅TODO List
- [ ] 거래 수정 리펙토링
- [ ] 거래 참여 리펙토링
- [ ] 거래 신고 리펙토링
