### ISSUE TITLE
거래 삭제, 유저 상태, 이미지 업로드 리펙토링

### ISSUE THREAD

**Issue by Kwontaehwon** [SWM-ChocoBread/N_bread_Server#208]
## 🔑Description

거래 삭제, 유저 상태, 이미지 업로드 리펙토링

<br>

## ✅TODO List
- [x] 거래 삭제
- [x] 유저 거래 상태
- [x] 쿠팡 이미지 업로드
- [x] S3 이미지 (배열) 업로드

**Comment by Kwontaehwon** [comment]
PR #209 에서 처리
