### ISSUE TITLE
refactor: event 리팩토링

### ISSUE THREAD

**Issue by kite707** [SWM-ChocoBread/N_bread_Server#219]
## 🔑Description
> event 도메인에 존재하는 api를 리팩토링합니다.

<br>

## ✅TODO List
- [ ] 전체 event 반환 api 리팩토링
- [ ] popup event반환 api 리팩토링
- [ ] event 생성 api 리팩토링
- [ ] event 이미지 업로드 api 리팩토링
