### ISSUE TITLE
refactor: 리팩토링 마무리

### ISSUE THREAD

**Issue by kite707** [SWM-ChocoBread/N_bread_Server#239]
## 🔑Description
> 리팩토링 완료 전 최종 점검

<br>

## ✅TODO List
- [x] 안쓰는 import문 삭제
- [x] Sequelize 삭제
- [x] responseMessage.OK 메세지 변경
- [x] Console.log 삭제 및 logger로 변경
- [x] success, fail 에 return 추가
- [x] 빌드 테스트
